[package]
name = "doh-proxy"
version = "0.1.13"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "A DNS-over-HTTPS (DoH) proxy"
keywords = ["dns","https","doh","proxy"]
license = "MIT"
homepage = "https://github.com/jedisct1/rust-doh"
repository = "https://github.com/jedisct1/rust-doh"
categories = ["asynchronous", "network-programming","command-line-utilities"]
edition = "2018"

[dependencies]
base64 = "0.10"
clap = "2"
futures = "0.1.26"
hyper = "0.12.27"
jemallocator = "0.3.0"
tokio = "0.1.18"
tokio-current-thread = "0.1.6"
tokio-timer = "0.2.10"
