[package]
name = "libdoh"
version = "0.2.1"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "DoH library for the rust-doh app"
keywords = ["dns","https","doh","proxy"]
license = "MIT"
homepage = "https://github.com/jedisct1/rust-doh"
repository = "https://github.com/jedisct1/rust-doh"
categories = ["asynchronous", "network-programming","command-line-utilities"]
edition = "2018"

[features]
default = []
tls = ["native-tls", "tokio-tls"]

[dependencies]
anyhow = "1.0"
byteorder = "1.3"
base64 = "0.11"
futures = { version = "0.3" }
hyper = { version = "0.13", default-features = false, features = ["stream"] }
native-tls = { version = "0.2.3", optional = true }
tokio = { version = "0.2", features = ["rt-threaded", "time", "tcp", "udp", "stream"] }
tokio-tls = { version = "0.3", optional = true }

[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
